// Main application class, generated by Spring Initializr.
// Must live in the top package so that @SpringBootApplication annotation
// can find all the components.

package voting_system;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import voting_system.model.Welcome;
import voting_system.service.VotingService;

@SpringBootApplication
public class VotingSystemApplication
{

    public static void main(String[] args) {
        SpringApplication.run(VotingSystemApplication.class, args);
    }

    // The initDB() @Bean is run automatically on startup, before the
    // @RestController is started.
    // The body could access command line argument args (but doesn't).
    // The fact that initDB() requires a VotingService argument tells Spring
    // to auto-configure and pass a VotingService instance, which initDB()
    // amends by adding more Welcome instances.
    @Bean
    public CommandLineRunner initDB(VotingService votingService) {
        return (args) -> {
            votingService.addWelcome(new Welcome("en", "Welcome"));
            votingService.addWelcome(new Welcome("fr", "Bienvenue"));
            votingService.addWelcome(new Welcome("de", "Herzlich Willkommen"));
        };
    }

}

