// Main application class, generated by Spring Initializr.
// Must live in the top package so that @SpringBootApplication annotation
// can find all the components.

package welcome;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import welcome.model.*;
import welcome.service.*;

@SpringBootApplication
public class WelcomeDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(WelcomeDemoApplication.class, args);
    }

    // The initDB() @Bean is run automatically on startup, before the
    // @RestController is started.
    // The body could access command line argument args (but doesn't).
    // The fact that initDB() requires a WelcomeService argument tells Spring
    // to auto-configure and pass a WelcomeService instance, which initDB()
    // amends by adding more Welcome instances.
    @Bean
    public CommandLineRunner initDB(WelcomeService ws) {
        return (args) -> {
            ws.addWelcome(new Welcome("en", "Welcome"));
            ws.addWelcome(new Welcome("fr", "Bienvenue"));
            ws.addWelcome(new Welcome("de", "Herzlich Willkommen"));
        };
    }

}
